In [2]:
import torch
import numpy as np

## Tensors

### initialize tensors

In [4]:
# Tensors can be created directly from data
data = [[1, 2],[3, 4]]
x_data = torch.tensor(data)
print(x_data)

tensor([[1, 2],
        [3, 4]])


In [6]:
# Tensors can be created from NumPy arrays 
np_array = np.array(data)
x_np = torch.from_numpy(np_array)
print(x_np)

tensor([[1, 2],
        [3, 4]], dtype=torch.int32)


In [8]:
x_ones = torch.ones_like(x_data) # retains the properties of x_data
print(f"Ones Tensor: \n {x_ones} \n")

x_rand = torch.rand_like(x_data, dtype=torch.float) # overrides the datatype of x_data
print(f"Random Tensor: \n {x_rand} \n")

Ones Tensor: 
 tensor([[1, 1],
        [1, 1]]) 

Random Tensor: 
 tensor([[0.4844, 0.1325],
        [0.0328, 0.4295]]) 



### Attributes

In [10]:
tensor = torch.rand(3,4)

print(f"Shape of tensor: {tensor.shape}")
print(f"Datatype of tensor: {tensor.dtype}")
print(f"Device tensor is stored on: {tensor.device}")

Shape of tensor: torch.Size([3, 4])
Datatype of tensor: torch.float32
Device tensor is stored on: cpu


### torch.cat

In [11]:
tensor = torch.ones(3, 3)
torch.cat([tensor, tensor, tensor])

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])

### In-place operations

In [13]:
# Operations that have a _ suffix are in-place. For example: x.copy_(y), x.t_(), will change x
tensor.add_(5)
print(tensor)
# In-place operations save some memory, but can be problematic when computing derivatives because of an immediate loss of history. 
# Hence, their use is discouraged.

tensor([[6., 6., 6.],
        [6., 6., 6.],
        [6., 6., 6.]])


### 与numpy转换

In [15]:
t = torch.ones(2,3)
print(f"t: \n {t}")
n = t.numpy()
print(f"n: \n {n}")

t: 
 tensor([[1., 1., 1.],
        [1., 1., 1.]])
n: 
 [[1. 1. 1.]
 [1. 1. 1.]]


In [17]:
n = np.ones(5)
t = torch.from_numpy(n)
print(f"t: {t}")
print(f"n: {n}")

t: tensor([1., 1., 1., 1., 1.], dtype=torch.float64)
n: [1. 1. 1. 1. 1.]


转换之后更改任意的变量，另一个变量也会变

## autograd

In [21]:
a = torch.tensor([2., 3.], requires_grad=True)
b = torch.tensor([6., 4.], requires_grad=True)

In [22]:
Q = 3*a**3 - b**2

In [23]:
external_grad = torch.tensor([1., 1.])
Q.backward(gradient=external_grad)

In [24]:
a.grad

tensor([36., 81.])

In [25]:
b.grad

tensor([-12.,  -8.])

## define nn

In [26]:
import torch.nn as nn
import torch.nn.functional as F

In [31]:
class Net(nn.Module):

    def __init__(self):
        super().__init__()
        # 1 input image channel, 6 output channels, 3x3 square convolution
        # kernel
        self.conv1 = nn.Conv2d(1, 6, 3)
        self.conv2 = nn.Conv2d(6, 16, 3)
        # an affine operation: y = Wx + b
        self.fc1 = nn.Linear(16 * 6 * 6, 120)  # 6*6 from image dimension
        self.fc2 = nn.Linear(120, 84)
        self.fc3 = nn.Linear(84, 10)

    def forward(self, x):
        # Max pooling over a (2, 2) window
        x = F.max_pool2d(F.relu(self.conv1(x)), (2, 2))
        # If the size is a square you can only specify a single number
        x = F.max_pool2d(F.relu(self.conv2(x)), 2)
        x = x.view(-1, self.num_flat_features(x))
        x = F.relu(self.fc1(x))
        x = F.relu(self.fc2(x))
        x = self.fc3(x)
        return x

    def num_flat_features(self, x):
        size = x.size()[1:]  # all dimensions except the batch dimension
        num_features = 1
        for s in size:
            num_features *= s
        return num_features


net = Net()
print(net)

Net(
  (conv1): Conv2d(1, 6, kernel_size=(3, 3), stride=(1, 1))
  (conv2): Conv2d(6, 16, kernel_size=(3, 3), stride=(1, 1))
  (fc1): Linear(in_features=576, out_features=120, bias=True)
  (fc2): Linear(in_features=120, out_features=84, bias=True)
  (fc3): Linear(in_features=84, out_features=10, bias=True)
)


In [35]:
input = torch.randn(1, 1, 32, 32)
out = net(input)
print(out)

tensor([[ 0.0083,  0.0344,  0.0534,  0.0212, -0.0443,  0.0325, -0.1267,  0.0035,
          0.0078, -0.0297]], grad_fn=<AddmmBackward>)


In [39]:
input = torch.randn(32, 32)

In [43]:
input.unsqueeze(0).shape

torch.Size([1, 32, 32])

In [58]:

x_data = torch.rand(3,4)


In [59]:
x_data

tensor([[0.1877, 0.7613, 0.2434, 0.2740],
        [0.3028, 0.8426, 0.6256, 0.6008],
        [0.5641, 0.2958, 0.1289, 0.7597]])

In [60]:
x_data.view(2, 6)

tensor([[0.1877, 0.7613, 0.2434, 0.2740, 0.3028, 0.8426],
        [0.6256, 0.6008, 0.5641, 0.2958, 0.1289, 0.7597]])