In [1]:
import torch
import numpy as np

## Tensors

### initialize tensors

In [4]:
# Tensors can be created directly from data
data = [[1, 2],[3, 4]]
x_data = torch.tensor(data)
print(x_data)

tensor([[1, 2],
        [3, 4]])


In [6]:
# Tensors can be created from NumPy arrays 
np_array = np.array(data)
x_np = torch.from_numpy(np_array)
print(x_np)

tensor([[1, 2],
        [3, 4]], dtype=torch.int32)


In [8]:
x_ones = torch.ones_like(x_data) # retains the properties of x_data
print(f"Ones Tensor: \n {x_ones} \n")

x_rand = torch.rand_like(x_data, dtype=torch.float) # overrides the datatype of x_data
print(f"Random Tensor: \n {x_rand} \n")

Ones Tensor: 
 tensor([[1, 1],
        [1, 1]]) 

Random Tensor: 
 tensor([[0.4844, 0.1325],
        [0.0328, 0.4295]]) 



### Attributes

In [10]:
tensor = torch.rand(3,4)

print(f"Shape of tensor: {tensor.shape}")
print(f"Datatype of tensor: {tensor.dtype}")
print(f"Device tensor is stored on: {tensor.device}")

Shape of tensor: torch.Size([3, 4])
Datatype of tensor: torch.float32
Device tensor is stored on: cpu


### torch.cat

In [11]:
tensor = torch.ones(3, 3)
torch.cat([tensor, tensor, tensor])

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])

### In-place operations

In [13]:
# Operations that have a _ suffix are in-place. For example: x.copy_(y), x.t_(), will change x
tensor.add_(5)
print(tensor)
# In-place operations save some memory, but can be problematic when computing derivatives because of an immediate loss of history. 
# Hence, their use is discouraged.

tensor([[6., 6., 6.],
        [6., 6., 6.],
        [6., 6., 6.]])


### 与numpy转换

In [15]:
t = torch.ones(2,3)
print(f"t: \n {t}")
n = t.numpy()
print(f"n: \n {n}")

t: 
 tensor([[1., 1., 1.],
        [1., 1., 1.]])
n: 
 [[1. 1. 1.]
 [1. 1. 1.]]


In [17]:
n = np.ones(5)
t = torch.from_numpy(n)
print(f"t: {t}")
print(f"n: {n}")

t: tensor([1., 1., 1., 1., 1.], dtype=torch.float64)
n: [1. 1. 1. 1. 1.]


转换之后更改任意的变量，另一个变量也会变